[package]
name = "iso8061-timestamp"
version = "0.1.3"
authors = ["novacrazy <novacrazy@gmail.com>"]
edition = "2018"
description = "High-performance ISO8061 Timestamp formatting and parsing"
keywords = ["date", "time", "iso8061", "formatting", "parsing"]
readme = "README.md"
categories = ["date-and-time", "no-std", "parser-implementations", "value-formatting"]
license = "MIT OR Apache-2.0"
include = ["src/**/*", "LICENSE-*", "README.md"]
documentation = "https://docs.rs/iso8061-timestamp"
repository = "https://github.com/Lantern-chat/iso8061-timestamp"

[features]
std = []
pg = ["postgres-types", "bytes", "std"]
nightly = []
default = ["std", "serde"]

[dependencies]
serde = { optional = true, version = "1" }
time = { version = "0.3", features = ["macros"] }
postgres-types = { optional = true, version = "0.2.2", features = ["with-time-0_3"] }
bytes = { optional = true, version = "1.1.0" }
generic-array = "0.14.4"

[dev-dependencies]
time = { version = "0.3", features = ["macros", "parsing", "formatting"] }
criterion = "0.3"
chrono = "0.4"

[[bench]]
name = "timestamp"
path = "benches/timestamp.rs"
harness = false

[profile.release]
opt-level = 3
lto = 'fat'
codegen-units = 1

[package.metadata.docs.rs]
features = ["serde", "pg"]